function dssObj = dsscompile(c)

if(isstruct(c) && isfield(c,'circuit') && isa(c.circuit,'dsscircuit'))
    if ~exist('fname','var') || isempty(fname)
        try
            circuitName = c.circuit.Name;
        catch
            circuitName = 'tmp';
        end
    else
        circuitName = fname;
    end
    % add energy meter at substation
    c = addEnergyMeter(c);
    pathtofile = dsswrite(c,circuitName,0,'tmp/dssget_tmp');
elseif isa(c,'char')
    pathtofile = c;
else
    error('Invalid c input. Must be a Opendss circuit (generated by dssconversion function) or path to main Opendss file.')
end

% Run Opendss simulation in Matlab
curDir = pwd;
[dssStartOK, dssObj, dssText] = dssStartup;
if dssStartOK
    np = which(pathtofile);
    if(~isempty(np))
        pathtofile = np;
    end
    dssText.command=['Compile "' pathtofile '"'];
    dssText.command='CalcVoltageBases';
else
    disp('dss Did Not Start. Check if Opendss is installed properly in your machine');
end
dssText.Command = ['cd "' curDir '"'];
cd(curDir);

end