function [ControlIter,Element,Action,VAVGPU10224,VPRIORPU0,kvar,Sec0] = importEventLog(filename, startRow, endRow)
%IMPORTFILE1 Import numeric data from a text file as column vectors.
%   [HOUR0,SEC0,ControlIter,Element,Action,VAVGPU10224,VPRIORPU0]
%   = IMPORTFILE1(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [HOUR0,SEC0,ControlIter,Element,Action,VAVGPU10224,VPRIORPU0]
%   = IMPORTFILE1(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [Hour0,Sec0,ControlIter,Element,Action,VAVGPU10224,VPRIORPU0]
%   = importfile1('ALPINE_EventLog.Txt',1, 3784);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/05/05 17:06:21

%% Initialize variables.
delimiter = ',';
if nargin<=2
	startRow = 1;
	endRow = inf;
end

%% Format string for each line of text:
%   column1: text (%s)
%	column2: text (%s)
%   column3: text (%s)
%	column4: text (%s)
%   column5: text (%s)
%	column6: text (%s)
%   column7: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%*[^\n]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
	frewind(fileID);
	dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
	for col=1:length(dataArray)
		dataArray{col} = [dataArray{col};dataArrayBlock{col}];
	end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Hour0 = dataArray{:, 1};
Sec0 = dataArray{:, 2};
ControlIter = dataArray{:, 3};
Element = dataArray{:, 4};
Action = dataArray{:, 5};
VAVGPU10224 = dataArray{:, 6};
VPRIORPU0 = dataArray{:, 7};
kvar=  dataArray{:, 8};

