function [o] = dssreadMonitorMode3(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [HOUR,TSEC,KWH,STATE,KWOUT,KWIN,LOSSES,IDLING,KWHCHG] =
%   IMPORTFILE(FILENAME) Reads data from text file FILENAME for the default
%   selection.
%
%   [HOUR,TSEC,KWH,STATE,KWOUT,KWIN,LOSSES,IDLING,KWHCHG] =
%   IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [hour,tsec,kWh,State,kWOut,kWIn,Losses,Idling,kWhChg] =
%   importfile('ieee37_Mon_mon_s_10.csv',2, 25);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2013/11/27 08:50:39

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
o.hour = dataArray{:, 1};
o.tsec = dataArray{:, 2};
o.kWh = dataArray{:, 3};
o.State = dataArray{:, 4};
o.kWOut = dataArray{:, 5};
o.kWIn = dataArray{:, 6};
o.Losses = dataArray{:, 7};
o.Idling = dataArray{:, 8};
o.kWhChg = dataArray{:, 9};

